#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const out = resolve(root, 'src/version.ts');
const content = `// Generated by scripts/generate-version.mjs. Do not edit.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(out, content);
